"use client"
import React, { useState, useMemo, useEffect } from "react";
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })
const metadata = {
  title: 'Remontada',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [pageUrl, setPageUrl] = useState('')
  const router = useRouter();

 {/*
  useEffect(() => {
    setPageUrl(window.location.pathname)
  })
*/}
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
            <NavBar />
            {children}
            <Footer />
          </div>
        {/*
        {pageUrl.substr(1, 4) == 'admi' ?
          <>
            {children}
          </>
          :
          <div>
            <NavBar />
            {children}
            <Footer />
          </div>
        }
      */}
      </body>
    </html>
  );
}

{/*
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
*/}
